<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class PostSendy {
	private $post2sendy_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'post2sendy_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'post2sendy_page_init' ) );
	}

	public function post2sendy_add_plugin_page() {
		add_options_page(
			'Post2Sendy', // page_title
			'Post2Sendy', // menu_title
			'manage_options', // capability
			'post2sendy', // menu_slug
			array( $this, 'post2sendy_create_admin_page' ) // function
		);
	}

/*
	public function post2sendy_add_plugin_page() {
		add_menu_page(
			'Post2Sendy', // page_title
			'Post2Sendy', // menu_title
			'manage_options', // capability
			'post2sendy', // menu_slug
			array( $this, 'post2sendy_create_admin_page' ), // function
			'dashicons-media-document', // icon_url
			3 // position
		);

                add_submenu_page( 
			'post2sendy', // parent_slug
			'Settings', // page_title
			'Settings', // menu_title
			'manage_options', // capability
			'post2sendy-settings', // menu_slug
			array( $this, 'post2sendy_create_admin_page' ) // function
                );
	}
*/

	public function post2sendy_create_admin_page() {
		$this->post2sendy_options = get_option( 'post2sendy_option_name' ); ?>

		<div class="wrap">
			<h2>Post2Sendy</h2>
			<!-- <p>Main settings are found here.</p> -->
			<?php //settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'post2sendy_option_group' );
					do_settings_sections( 'post2sendy-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function post2sendy_page_init() {
		register_setting(
			'post2sendy_option_group', // option_group
			'post2sendy_option_name', // option_name
			array( $this, 'post2sendy_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'post2sendy_setting_section', // id
			'Email Settings', // title
			array( $this, 'post2sendy_section_info' ), // callback
			'post2sendy-admin' // page
		);

		add_settings_field(
			'server_url_0', // id
			'Server URL', // title
			array( $this, 'server_url_0_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'api_key_1', // id
			'API Key', // title
			array( $this, 'api_key_1_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'brand_id_2', // id
			'Brand ID', // title
			array( $this, 'brand_id_2_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'list_id_3', // id
			'List ID', // title
			array( $this, 'list_id_3_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'template_url_4', // id
			'Template URL', // title
			array( $this, 'template_url_4_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'from_name_5', // id
			'From Name', // title
			array( $this, 'from_name_5_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'from_email_6', // id
			'From Email', // title
			array( $this, 'from_email_6_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'reply_to_7', // id
			'Reply To', // title
			array( $this, 'reply_to_7_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'campaign_title_format_8', // id
			'Campaign Title Format', // title
			array( $this, 'campaign_title_format_8_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'email_subject_format_9', // id
			'Email Subject Format', // title
			array( $this, 'email_subject_format_9_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'email_content_format_10', // id
			'Email Content Format', // title
			array( $this, 'email_content_format_10_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'track_opens_11', // id
			'Track Opens', // title
			array( $this, 'track_opens_11_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'track_clicks_12', // id
			'Track Clicks', // title
			array( $this, 'track_clicks_12_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);

		add_settings_field(
			'default_email_status_13', // id
			'Default Email Status', // title
			array( $this, 'default_email_status_13_callback' ), // callback
			'post2sendy-admin', // page
			'post2sendy_setting_section' // section
		);
	}

	public function post2sendy_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['server_url_0'] ) ) {
			$sanitary_values['server_url_0'] = sanitize_text_field( $input['server_url_0'] );
		}

		if ( isset( $input['api_key_1'] ) ) {
			$sanitary_values['api_key_1'] = sanitize_text_field( $input['api_key_1'] );
		}

		if ( isset( $input['brand_id_2'] ) ) {
			$sanitary_values['brand_id_2'] = sanitize_text_field( $input['brand_id_2'] );
		}

		if ( isset( $input['list_id_3'] ) ) {
			$sanitary_values['list_id_3'] = sanitize_text_field( $input['list_id_3'] );
		}

		if ( isset( $input['template_url_4'] ) ) {
			$sanitary_values['template_url_4'] = sanitize_text_field( $input['template_url_4'] );
		}

		if ( isset( $input['from_name_5'] ) ) {
			$sanitary_values['from_name_5'] = sanitize_text_field( $input['from_name_5'] );
		}

		if ( isset( $input['from_email_6'] ) ) {
			$sanitary_values['from_email_6'] = sanitize_text_field( $input['from_email_6'] );
		}

		if ( isset( $input['reply_to_7'] ) ) {
			$sanitary_values['reply_to_7'] = sanitize_text_field( $input['reply_to_7'] );
		}

		if ( isset( $input['campaign_title_format_8'] ) ) {
			$sanitary_values['campaign_title_format_8'] = sanitize_text_field( $input['campaign_title_format_8'] );
		}

		if ( isset( $input['email_subject_format_9'] ) ) {
			$sanitary_values['email_subject_format_9'] = sanitize_text_field( $input['email_subject_format_9'] );
		}

		if ( isset( $input['email_content_format_10'] ) ) {
			$sanitary_values['email_content_format_10'] = esc_textarea( $input['email_content_format_10'] );
		}

		if ( isset( $input['track_opens_11'] ) ) {
			$sanitary_values['track_opens_11'] = $input['track_opens_11'];
		}

		if ( isset( $input['track_clicks_12'] ) ) {
			$sanitary_values['track_clicks_12'] = $input['track_clicks_12'];
		}

		if ( isset( $input['default_email_status_13'] ) ) {
			$sanitary_values['default_email_status_13'] = $input['default_email_status_13'];
		}

		return $sanitary_values;
	}

	public function post2sendy_section_info() {
		
	}

	public function server_url_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="post2sendy_option_name[server_url_0]" id="server_url_0" value="%s">',
			isset( $this->post2sendy_options['server_url_0'] ) ? esc_attr( $this->post2sendy_options['server_url_0']) : ''
		);
		echo "<br>The URL for your Sendy server with no trailing slash. For example: https://yourname.com";
	}

	public function api_key_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="post2sendy_option_name[api_key_1]" id="api_key_1" value="%s">',
			isset( $this->post2sendy_options['api_key_1'] ) ? esc_attr( $this->post2sendy_options['api_key_1']) : ''
		);
		echo "<br>The API Key which you can get from Sendy's settings page.";
	}

	public function brand_id_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="post2sendy_option_name[brand_id_2]" id="brand_id_2" value="%s">',
			isset( $this->post2sendy_options['brand_id_2'] ) ? esc_attr( $this->post2sendy_options['brand_id_2']) : ''
		);
		echo "<br>Since Sendy supports multiple brands, you will need to specify the ID of the brand you intend to use. This will be an integer.";
	}

	public function list_id_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="post2sendy_option_name[list_id_3]" id="list_id_3" value="%s">',
			isset( $this->post2sendy_options['list_id_3'] ) ? esc_attr( $this->post2sendy_options['list_id_3']) : ''
		);
		echo "<br>Each subscriber list has a unique hash ID of letters and numbers. You can get this from Sendy by looking at your lists.";
	}

	public function template_url_4_callback() {
		printf(
			'<input class="regular-text" type="text" name="post2sendy_option_name[template_url_4]" id="template_url_4" value="%s">',
			isset( $this->post2sendy_options['template_url_4'] ) ? esc_attr( $this->post2sendy_options['template_url_4']) : ''
		);
		echo "<br>Specify the URL where to retrieve an email template to use. This should include a [CONTENT] placeholder which will be replaced with the email message specified below.";
	}

	public function from_name_5_callback() {
		printf(
			'<input class="regular-text" type="text" name="post2sendy_option_name[from_name_5]" id="from_name_5" value="%s">',
			isset( $this->post2sendy_options['from_name_5'] ) ? esc_attr( $this->post2sendy_options['from_name_5']) : ''
		);
		echo "<br>The name from which emails will be sent.";
	}

	public function from_email_6_callback() {
		printf(
			'<input class="regular-text" type="text" name="post2sendy_option_name[from_email_6]" id="from_email_6" value="%s">',
			isset( $this->post2sendy_options['from_email_6'] ) ? esc_attr( $this->post2sendy_options['from_email_6']) : ''
		);
		echo "<br>The email address from which emails will be sent.";
	}

	public function reply_to_7_callback() {
		printf(
			'<input class="regular-text" type="text" name="post2sendy_option_name[reply_to_7]" id="reply_to_7" value="%s">',
			isset( $this->post2sendy_options['reply_to_7'] ) ? esc_attr( $this->post2sendy_options['reply_to_7']) : ''
		);
		echo "<br>If an email recipient replies to an email, this will be address to which replies will be sent.";
	}

	public function campaign_title_format_8_callback() {
		printf(
			'<input class="regular-text" type="text" name="post2sendy_option_name[campaign_title_format_8]" id="campaign_title_format_8" value="%s">',
			isset( $this->post2sendy_options['campaign_title_format_8'] ) ? esc_attr( $this->post2sendy_options['campaign_title_format_8']) : ''
		);
		echo "<br>This will be used to form the name of the Sendy email Campaign Name. You can use the [TITLE] placeholder if you want to include the title of the blog post.";
	}

	public function email_subject_format_9_callback() {
		printf(
			'<input class="regular-text" type="text" name="post2sendy_option_name[email_subject_format_9]" id="email_subject_format_9" value="%s">',
			isset( $this->post2sendy_options['email_subject_format_9'] ) ? esc_attr( $this->post2sendy_options['email_subject_format_9']) : ''
		);
		echo "<br>The subject of the email sent to the subscriber list. You can use the [TITLE] placeholder if you want to include that in the subject.";
	}

	public function email_content_format_10_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="post2sendy_option_name[email_content_format_10]" id="email_content_format_10">%s</textarea>',
			isset( $this->post2sendy_options['email_content_format_10'] ) ? esc_attr( $this->post2sendy_options['email_content_format_10']) : ''
		);
		echo "<br>The content of the email which will replace [CONTENT] in the template. You can also use placeholders such as [YEAR], [AUTHOR], [TITLE], [POST_URL], [POST_CONTENT], and [POST_SUMMARY].";
	}

	public function track_opens_11_callback() {
		printf(
			'<input type="checkbox" name="post2sendy_option_name[track_opens_11]" id="track_opens_11" value="track_opens_11" %s>',
			( isset( $this->post2sendy_options['track_opens_11'] ) && $this->post2sendy_options['track_opens_11'] === 'track_opens_11' ) ? 'checked' : ''
		);
		echo "<br>Whether or not Sendy should track email opens.";
	}

	public function track_clicks_12_callback() {
		printf(
			'<input type="checkbox" name="post2sendy_option_name[track_clicks_12]" id="track_clicks_12" value="track_clicks_12" %s>',
			( isset( $this->post2sendy_options['track_clicks_12'] ) && $this->post2sendy_options['track_clicks_12'] === 'track_clicks_12' ) ? 'checked' : ''
		);
		echo "<br>Whether or not Sendy should track email clicks.";
	}

	public function default_email_status_13_callback() {
		?> <select name="post2sendy_option_name[default_email_status_13]" id="default_email_status_13">
			<?php $selected = (isset( $this->post2sendy_options['default_email_status_13'] ) && $this->post2sendy_options['default_email_status_13'] === 'Draft') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>Draft</option>
			<?php $selected = (isset( $this->post2sendy_options['default_email_status_13'] ) && $this->post2sendy_options['default_email_status_13'] === 'Publish') ? 'selected' : '' ; ?>
			<option <?php echo $selected; ?>>Publish</option>
		</select> 
        <?php
	}

}
if ( is_admin() )
	$post2sendy = new PostSendy();

/* 
 * Retrieve this value with:
 * $post2sendy_options = get_option( 'post2sendy_option_name' ); // Array of All Options
 * $server_url_0 = $post2sendy_options['server_url_0']; // Server URL
 * $api_key_1 = $post2sendy_options['api_key_1']; // API Key
 * $brand_id_2 = $post2sendy_options['brand_id_2']; // Brand ID
 * $list_id_3 = $post2sendy_options['list_id_3']; // List ID
 * $template_url_4 = $post2sendy_options['template_url_4']; // Template URL
 * $from_name_5 = $post2sendy_options['from_name_5']; // From Name
 * $from_email_6 = $post2sendy_options['from_email_6']; // From Email
 * $reply_to_7 = $post2sendy_options['reply_to_7']; // Reply To
 * $campaign_title_format_8 = $post2sendy_options['campaign_title_format_8']; // Campaign Title Format
 * $email_subject_format_9 = $post2sendy_options['email_subject_format_9']; // Email Subject Format
 * $email_content_format_10 = $post2sendy_options['email_content_format_10']; // Email Content Format
 * $track_opens_11 = $post2sendy_options['track_opens_11']; // Track Opens
 * $track_clicks_12 = $post2sendy_options['track_clicks_12']; // Track Clicks
 * $default_email_status_13 = $post2sendy_options['default_email_status_13']; // Default Email Status
 */

/*
function edit_admin_menus() {
    global $menu;
    global $submenu;

    $submenu[post2sendy][0][0] = "Email Settings";
    $submenu[post2sendy][1][0] = "Test2";
}
add_action( 'admin_menu', 'edit_admin_menus' );
*/
